### ISSUE TITLE
Can't backspace during text entry

### ISSUE THREAD

**Issue by mr337** [nielssp/ctodo#2]
Hi,

Just found your app and giving it a try for my daily driver. One thing I encountered is I cannot backspace if I typed something wrong. I can arrow to the left and use my delete key.

![2016-01-08-104200_396x57_scrot](https://cloud.githubusercontent.com/assets/413937/12203423/86cb925c-b5f4-11e5-9cd5-c418520bb5ec.png)

Any ideas?

**Comment by nielssp** [comment]
Which terminal emulator are you using? I just tried in xterm, and indeed backspace didn't work. I have added another keycode for backspace, which seemed to fix the issue for xterm, can you try out the newest commit?

**Comment by mr337** [comment]
Bam your spot on, I'm using xterm.

**Comment by mr337** [comment]
Can confirm, backspace is now working in xterm, Thx!

**Comment by nielssp** [comment]
Awesome, thanks for making me aware of the issue
